### ISSUE TITLE
Cannot pop Cogroup

### ISSUE THREAD

**Issue by poluhh** [marshallward/f90nml#139]
If a namelist is repeated starting from version 1.4 a Cogroup is created. Consider the following file `tmp.nml`:
```
&repeat a=1 b=0 c=0 /
&repeat a=0 b=1 c=0 /
&repeat a=0 b=0 c=1 /
```
If I want to delete the namelist `repeat` I would simply pop it with previous versions. However, this raises an error with version 1.4:
```
% python
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import f90nml
>>> f90nml.__version__
'1.4'
>>> with open("tmp.nml") as nmlfile:
...     nmlist = f90nml.read(nmlfile)
... 
>>> nmlist.keys()
_NamelistKeysView(Namelist([('repeat', Namelist([('a', 1), ('b', 0), ('c', 0)])), ('repeat', Namelist([('a', 0), ('b', 1), ('c', 0)])), ('repeat', Namelist([('a', 0), ('b', 0), ('c', 1)]))]))
>>> nmlist.pop("repeat")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zmaw/u301608/Documents/scratch_mi-theo/.conda/envs/updated_env/lib/python3.10/site-packages/f90nml/namelist.py", line 158, in __delitem__
    super(Namelist, self).__delitem__(gkey)
KeyError: 'repeat'
```

**Comment by poluhh** [comment]
Works just fine! Thanks a lot

**Comment by marshallward** [comment]
Great, I will do a release later today.
