### ISSUE TITLE
Write fail when an empty list is provided

### ISSUE THREAD

**Issue by william-dawson** [marshallward/f90nml#140]
Minimal example:
```
import f90nml
from io import StringIO

# Works
ofile = StringIO()
data = {"sec": {"a": 3, "b": [4]}}
f90nml.write(data, ofile)
print(ofile.getvalue())

# Fails                                                                                                                                  
ofile = StringIO()
data = {"sec": {"a": 3, "b": []}}
f90nml.write(data, ofile)
print(ofile.getvalue())
```

Program output:
```
&sec
    a = 3
    b = 4
/

Traceback (most recent call last):
  File "/Users/wddawson/Desktop/nml_check/main.py", line 17, in <module>
    f90nml.write(data, ofile)
  File "/Users/wddawson/miniconda3/envs/fix_nml/lib/python3.10/site-packages/f90nml/__init__.py", line 82, in write
    nml_in.write(nml_path, force=force, sort=sort)
  File "/Users/wddawson/miniconda3/envs/fix_nml/lib/python3.10/site-packages/f90nml/namelist.py", line 575, in write
    self._writestream(nml_file, sort)
  File "/Users/wddawson/miniconda3/envs/fix_nml/lib/python3.10/site-packages/f90nml/namelist.py", line 679, in _writestream
    self._write_nmlgrp(grp_name, grp_vars, nml_file, sort)
  File "/Users/wddawson/miniconda3/envs/fix_nml/lib/python3.10/site-packages/f90nml/namelist.py", line 703, in _write_nmlgrp
    for v_str in self._var_strings(v_name, v_val, v_start=v_start):
  File "/Users/wddawson/miniconda3/envs/fix_nml/lib/python3.10/site-packages/f90nml/namelist.py", line 886, in _var_strings
    if val_strs and v_values[-1] is None:
IndexError: list index out of range

```

Version 1.4 which was downloaded and installed from the git repository (`731204eb9deb991e9a397cd49d0a261d2a14537c`). I created a fresh conda environment, installed pip, cloned f90nml to my directory, entered that directory, and ran `pip install .` 

Python: `3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:45:10) [Clang 12.0.1 ]`

OS: Mac OSX 12.3.1

**Comment by marshallward** [comment]
Thanks, I can replicate this.  It seems isolated to the printing of the namelist.

I can't think of a way to uniquely express a zero-element list inside of a namelist, but certainly they can exist in Fortran, so that is another reason to get this right.

**Comment by marshallward** [comment]
Can you test this branch?

https://github.com/marshallward/f90nml/tree/constructor_empty_list

`[]` and `None` are now handled identically.

**Comment by william-dawson** [comment]
Thanks for the quick response! It seems to work for me!
