### ISSUE TITLE
del with upper case not working in versions > 1.3.1

### ISSUE THREAD

**Issue by mandresm** [marshallward/f90nml#142]
The following python script works with version `1.3.1` of `f90nml`:
```
import f90nml

parser = f90nml.Parser()

nml = parser.reads("&section var1='it prints!' var2=2 /")

print(nml["section"]["Var1"])
print()
del nml["section"]["Var1"]
```
However, when I try to run the same script with `f90nml>=1.4.0` I get the following error:
```
Traceback (most recent call last):
  File "nml_example.py", line 9, in <module>
    del nml["section"]["Var1"]
  File "/home/ollie/mandresm/.local/lib/python3.7/site-packages/f90nml/namelist.py", line 162, in __delitem__
    super(Namelist, self).__delitem__(key)
KeyError: 'Var1'

```
When I substitute `del nml["section"]["Var1"]` by the lower-case version `fel nml["section"]["var1"]` it all works again.

Am I using it wrong and I should use only lower case keys or is this really a bug since it works for the case of getting the item but not deleting it?

**Comment by mandresm** [comment]
thanks :)

**Comment by mandresm** [comment]
Thanks for the very fast solution! I'll close the issue now.
