### ISSUE TITLE
Lists of namelists cannot be added

### ISSUE THREAD

**Issue by rhfogh** [marshallward/f90nml#167]
A namelist containing a list of namelists created in Python cannot be written to file and throws an error.

The test program:

import f90nml
data = f90nml.Namelist()
data["dict1"] = f90nml.Namelist(attr1=1, attr2=2)
data["list1"] = []
data["list1"].append(f90nml.Namelist(attr3=3, attr4=4))
data["list1"].append(f90nml.Namelist(attr3=5, attr4=6))
data.write("somefile.out")

gives  - for Python 3.8 and f90nml versions 1.4.1, 1.4.3, and 1.4.4

Traceback (most recent call last):
  File "/home/rhfogh/Software/scripts/test_f90nml.py", line 9, in <module>
    data.write("/home/rhfogh/calc/mxcube_data/f90nmltst5.out")
  File "/alt/rhfogh/Software/miniconda3/envs/mxcubeqt/lib/python3.8/site-packages/f90nml/namelist.py", line 578, in write
    self._writestream(nml_file, sort)
  File "/alt/rhfogh/Software/miniconda3/envs/mxcubeqt/lib/python3.8/site-packages/f90nml/namelist.py", line 677, in _writestream
    self._write_nmlgrp(grp_name, grp_vars, nml_file, sort)
  File "/alt/rhfogh/Software/miniconda3/envs/mxcubeqt/lib/python3.8/site-packages/f90nml/namelist.py", line 693, in _write_nmlgrp
    for v_name, v_val in grp_vars.items():
AttributeError: 'list' object has no attribute 'items'

With the output:

&dict1
    attr1 = 1
    attr2 = 2
/

&list1

When running with Python 3.8 and  f90nml version 1.3.1 the test works and you get the desired result:

&dict1
    attr1 = 1
    attr2 = 2
/

&list1
    attr3 = 3
    attr4 = 4
/

&list1
    attr3 = 5
    attr4 = 6
/

**Comment by marshallward** [comment]
Assuming there are no unexpected issues, I think we could modify things so that `data['list1'] = []` is equivalent to `data.create_cogroup('list1')` and the `data['list1'].append()` calls are equivalent to `data.add_cogroup('list1', ...)`.

**Comment by rhfogh** [comment]
@marshallward That would be great. Now that I understand how it ought to work (thanks!) I could also rewrite our code to use the cogroups, but it would be  kind of neat that you can use the standard Python datatype, a list. 

One question springs to mind, though: What should happen if you did data.create_cogroup('list1') followed by a single data.add_cogroup('list1', ...) call, or even none? Or, equivalently, if you added an empty list or a list with a single member? In normal Python logic you would expect the result to be an empty list, or a list with one member as appropriate, but with Fortran logic you might expect something else. If you cannot get the Python-expected behaviour from adding Python lists without confusing the Fortran expectations, it might be better to force people to use the cogroup syntax after all; that way there would be fewer surprises. If that is the preferred solution I would vote for a better error message, though, something about adding an illegal type.

**Comment by marshallward** [comment]
`Cogroup` was originally meant to be an internal type that was invisible to the user, but I did eventually decide to create a small API during testing.  It is a concise way to set them up, but it does add more concepts for the user to absorb.

`data.create_cogroup('list1')` sets up the metadata to track `list1` as a cogroup.  If there are no `list1` groups, then `data['list1']` returns an empty list.  But if you iterate over values of `data`, then `data` will appear empty, with no reference to `list1`.

If `list1` is declared to be a cogroup, then `data['list1']` returns a list of `Namelist` values.  If there's one `list1` group, then it's a list of one.  I can't recall if this is different from v1.3.  Iteration will return the group, not the list.

In Fortran the namelist would be read serially, so `data['list1']` would probably simply return the first group in the list, with subsequent reads giving the next in the list, and so forth, which I don't think anyone wants.  I suppose we are trying to build a datatype that exists inbetween the Fortran and Python environments.

I think there is certainly a lot of nuance here, which you are doing a great job of exposing.  My goal at the time was to support while preserving the old API for reading.  It might be worth writing up a small document about Cogroups at some point.

Thanks very much for your feedback!  I confess that I don't think much about namelist generation within Python.  Unsurprisingly, I think most of the bug reports are from users who do this!

I would like to keep this issue open for a bit longer, while I test out list assignment to `Namelist`.  If it doesn't affect the other uses of `Namelist` (or if I finally decide to split it into `Namelist`, `Group`, `DerivedType`), then I think it would work nicely.

**Comment by marshallward** [comment]
@m-n-o For now, the only way to generate a `Namelist` with duplicate keys is to follow the Cogroup syntax, [as in the example above](https://github.com/marshallward/f90nml/issues/167#issuecomment-2501349609).

Perhaps something like this:
```
from f90nml import Namelist
nml_cfg_edit = Namelist(namrun=Namelist(x=1,y=2), namsbc_blk=Namelist(u=1,v=2))
nml_cfg_edit.create_cogroup('nambdy_dta')
nml_cfg_edit.add_cogroup('nambdy_dta', Namelist(cn_dir=1))
nml_cfg_edit.add_cogroup('nambdy_dta', Namelist(cn_dir=2))
nml_cfg_edit.add_cogroup('nambdy_dta', Namelist(cn_dir=3))
print(nml_cfg_edit)
```
I agree that the syntax is a little odd.  As mentioned above, it may be possible to improve the API and associate these functions with native list and dict dunder functions.

**Comment by m-n-o** [comment]
Thanks!
Your method is working and the Namelist object is being created. But I also have trouble with patching the original namelist file.
I can just read the source text, change the parameters and write it down, but this approach breaks the original formatting and comments. Therefore, I prefer patching.

Next code 
```python
f90nml.patch("/path/namelist_cfg", nml_cfg_edit, out_path="/path/namelist_cfg_tmplt")
```
causes next error: `AttributeError: 'Cogroup' object has no attribute 'items'`

**Comment by marshallward** [comment]
I suspect this is simply not possible at the moment.  It would require modifying `patch` to work with Cogroups, which seems to not be possible at the moment.

I don't know if there will be time to look into this, but I'll open an issue on this topic.
